# Generated by Django 5.2.3 on 2025-07-20 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FabricLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=100, unique=True)),
                ('invoice_no', models.CharField(max_length=100)),
                ('fabric_type', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('meter', models.FloatField()),
                ('rate', models.FloatField()),
                ('purchase_date', models.DateField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabric.vendor')),
            ],
        ),
    ]
