# Generated by Django 5.2.3 on 2025-07-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabriclot',
            name='discount',
            field=models.FloatField(default=0, help_text='Discount amount before GST'),
        ),
        migrations.AddField(
            model_name='fabriclot',
            name='gst',
            field=models.FloatField(default=0, help_text='GST % (e.g., enter 5 for 5%)'),
            preserve_default=False,
        ),
    ]
