# Generated by Django 5.2.3 on 2025-07-20 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0002_fabriclot_discount_fabriclot_gst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabriclot',
            name='color',
        ),
        migrations.RemoveField(
            model_name='fabriclot',
            name='meter',
        ),
        migrations.AlterField(
            model_name='fabriclot',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='fabriclot',
            name='gst',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='fabriclot',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='FabricColorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('meter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='fabric.fabriclot')),
            ],
        ),
    ]
