# Generated by Django 5.2.3 on 2025-07-20 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0003_remove_fabriclot_color_remove_fabriclot_meter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobWorkIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobWorkFabricItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_issued', models.FloatField()),
                ('color_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabric.fabriccolordetail')),
                ('fabric_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabric.fabriclot')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fabric.jobworkissue')),
            ],
        ),
        migrations.AddField(
            model_name='jobworkissue',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabric.manufacturer'),
        ),
    ]
