# Generated by Django 5.2.3 on 2025-08-14 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0004_jobworkissue_manufacturer_jobworkfabricitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobWorkIssueSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('job_work_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='fabric.jobworkissue')),
            ],
        ),
    ]
